### PR TITLE
Upgrade to split stream and messaging versions

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
(not fully tested yet)

**Comment by jponge** [comment]
@cescoffier I jumped straight to `demo5` and running `demo5-web` fails on classes not found: the rx-ified Vert.x Kafka classes.

Any idea?

```
19:30:41.683 [main] ERROR me.escoffier.reactive_summit.demo5.WebApp - Unable to start the application
org.jboss.weld.exceptions.DeploymentException: null
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:499) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:801) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at net.redpipe.cdi.CdiPlugin.lambda$preInit$3(CdiPlugin.java:77) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:36) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactiverse.reactivecontexts.propagators.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:30) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactiverse.reactivecontexts.propagators.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:30) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactiverse.reactivecontexts.propagators.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:30) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactiverse.reactivecontexts.propagators.rxjava2.ContextPropagatorOnCompletableAssemblyAction$ContextPropagatorCompletable.subscribeActual(ContextPropagatorOnCompletableAssemblyAction.java:30) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactiverse.reactivecontexts.propagators.rxjava2.ContextPropagatorOnSingleCreateAction$ContextCapturerSingle.onSuccess(ContextPropagatorOnSingleCreateAction.java:51) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactiverse.reactivecontexts.propagators.rxjava2.ContextPropagatorOnSingleCreateAction$ContextCapturerSingle.onSuccess(ContextPropagatorOnSingleCreateAction.java:51) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Single.subscribe(Single.java:3438) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactiverse.reactivecontexts.propagators.rxjava2.ContextPropagatorOnSingleAssemblyAction$ContextPropagatorSingle.subscribeActual(ContextPropagatorOnSingleAssemblyAction.java:30) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Single.subscribe(Single.java:3438) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at net.redpipe.engine.core.Server.lambda$start$0(Server.java:99) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Single.subscribe(Single.java:3438) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Single.subscribe(Single.java:3438) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleDelayWithCompletable.subscribeActual(SingleDelayWithCompletable.java:36) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Single.subscribe(Single.java:3438) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2234) [demo5-web-1.0-SNAPSHOT.jar:?]
	at io.reactivex.Completable.subscribe(Completable.java:2307) [demo5-web-1.0-SNAPSHOT.jar:?]
	at me.escoffier.reactive_summit.demo5.WebApp.main(WebApp.java:14) [demo5-web-1.0-SNAPSHOT.jar:?]
Caused by: javax.enterprise.event.ObserverException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_181]
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	... 48 more
Caused by: java.lang.NoClassDefFoundError: io/vertx/reactivex/kafka/client/consumer/KafkaConsumer
	at io.smallrye.reactive.messaging.kafka.KafkaSource.<init>(KafkaSource.java:21) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.kafka.KafkaSource.create(KafkaSource.java:42) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider.createPublisher(KafkaMessagingProvider.java:34) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider$Proxy$_$$_WeldClientProxy.createPublisher(Unknown Source) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory.createSourceFromConfig(ConfiguredStreamFactory.java:130) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory.lambda$initialize$4(ConfiguredStreamFactory.java:100) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_181]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory.initialize(ConfiguredStreamFactory.java:100) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory$Proxy$_$$_WeldClientProxy.initialize(Unknown Source) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_181]
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:80) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.ReactiveMessagingExtension.afterDeploymentValidation(ReactiveMessagingExtension.java:52) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	... 48 more
Caused by: java.lang.ClassNotFoundException: io.vertx.reactivex.kafka.client.consumer.KafkaConsumer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at io.smallrye.reactive.messaging.kafka.KafkaSource.<init>(KafkaSource.java:21) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.kafka.KafkaSource.create(KafkaSource.java:42) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider.createPublisher(KafkaMessagingProvider.java:34) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider$Proxy$_$$_WeldClientProxy.createPublisher(Unknown Source) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory.createSourceFromConfig(ConfiguredStreamFactory.java:130) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory.lambda$initialize$4(ConfiguredStreamFactory.java:100) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_181]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory.initialize(ConfiguredStreamFactory.java:100) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory$Proxy$_$$_WeldClientProxy.initialize(Unknown Source) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_181]
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:80) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at io.smallrye.reactive.messaging.ReactiveMessagingExtension.afterDeploymentValidation(ReactiveMessagingExtension.java:52) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35) ~[demo5-web-1.0-SNAPSHOT.jar:?]
	... 48 more
```

**Comment by jponge** [comment]
Interim solution, I added

```xml
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-kafka-client</artifactId>
  <version>${vertx.version}</version>
</dependency>
```

but this may reveal a problem with the SmallRye dependencies.

**Comment by jponge** [comment]
Strange thing: I had to run `demo5-web` using `mvn vertx:run`, running the fatjar did not expose `http://localhost:9000/webroot/index.html`

**Comment by cescoffier** [comment]
Yes, I've seen this issue with vertx:run. I've to admit that I didn't investigated much. I believe it just can't find the resources. It might be redpipe specific.

**Comment by cescoffier** [comment]
The kafka dependency is interesting, as it should retrieve it from SmallRye Reactive Messaging. I will have a look.

**Comment by cescoffier** [comment]
Thank you! It's great to have this demo up to date.

**Pull request merged**
